// Code generated by goctl. DO NOT EDIT.
package types

type InviteCreateReq struct {
	Count    int    `json:"count"`
	Password string `json:"password"`
}

type InviteCreateResp struct {
	InviteCodes interface{} `json:"invite_codes"`
}

type InviteHistory struct {
	InviteCredit  int    `json:"invite_credit"`
	ChildId       int64  `json:"child_id"`
	ChildUserName string `json:"child_user_name"`
	Avatar        string `json:"avatar"`
	CreateTime    int64  `json:"create_time"`
}

type InviteHistoryReq struct {
	Id    int64  `json:"id" validate:"required"` // 用户或机器人的唯一标识符,使用64位整数
	Token string `json:"token" validate:"required"`
}

type InviteHistoryResp struct {
	TotalInviteCount   int             `json:"total_invite_count"`
	SuccessInviteCount int             `json:"success_invite_count"`
	InviteHistorys     []InviteHistory `json:"invite_historys"`
}

type InviteListReq struct {
	Id    int64  `json:"id" validate:"required"` // 用户或机器人的唯一标识符,使用64位整数
	Token string `json:"token" validate:"required"`
}

type InviteListResp struct {
	TotalCredit        int    `json:"total_credit"` // 只算邀请的积分
	TotalInviteCount   int    `json:"total_invite_count"`
	SuccessInviteCount int    `json:"success_invite_count"`
	SelfCode           string `json:"self_code"`
	ParentCode         string `json:"parent_code"`
}

type InviteVerifyReq struct {
	Id         int64  `json:"id" validate:"required"` // 用户或机器人的唯一标识符,使用64位整数
	InviteCode string `json:"invite_code" validate:"required"`
	Token      string `json:"token" validate:"required"`
}

type InviteVerifyResp struct {
	InviteCredit    int  `json:"invite_credit"`
	IsInviteSuccess bool `json:"is_invite_success"`
}
