// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	invite "github.com/Savvy-Gameing/backend/internal/handler/invite"
	sys "github.com/Savvy-Gameing/backend/internal/handler/sys"
	"github.com/Savvy-Gameing/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/invite_history",
				Handler: invite.InviteHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/invite_list",
				Handler: invite.InviteListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/invite_verify",
				Handler: invite.InviteVerifyHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/invite_create",
				Handler: sys.InviteCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
